/**
 * Generated from the OpenAPI 3.1 artifact contracts/openapi-v1.json.
 * Generator: openapi-typescript 7.13.0.
 * Runtime: openapi-fetch 0.17.0.
 *
 * Do not edit this file. Transport and feature policy belong in composition
 * adapters below Platform/Api.
 */
import createClient from "openapi-fetch";

export type components = {
  schemas: {
    "ProblemDetails": {
      type: string;
      title: string;
      status: number;
      detail: string;
      instance?: string | null;
      code: string;
      traceId: string;
      errors: Array<{
        code: string;
        message: string;
        target?: string | null;
      }>;
    };
    "OrdersStatusResponse": {
      module: string;
      dependencies: Array<string>;
    };
  };
};

export type ProblemDetails = components["schemas"]["ProblemDetails"];

export type paths = {
  "/api/v1/orders/status": {
    get: {
        responses: {
          "200": {
            content: {
              "application/json": components["schemas"]["OrdersStatusResponse"];
            };
          };
          "500": {
            content: {
              "application/problem+json": components["schemas"]["ProblemDetails"];
            };
          };
        };
      };
  };
  "/api/v1/orders/status/permissioned": {
    get: {
        responses: {
          "200": {
            content: {
              "application/json": components["schemas"]["OrdersStatusResponse"];
            };
          };
          "403": {
            content: {
              "application/problem+json": components["schemas"]["ProblemDetails"];
            };
          };
          "500": {
            content: {
              "application/problem+json": components["schemas"]["ProblemDetails"];
            };
          };
        };
      };
  };
};

export const createGeneratedClient = (baseUrl: string) =>
  createClient<paths>({ baseUrl });
