/**
 * Generated from the OpenAPI 3.1 artifact contracts/openapi-v1.json.
 * Generator: openapi-typescript 7.13.0.
 * Runtime: openapi-fetch 0.17.0.
 * Contract SHA-256: 401e7e4d6cb38f1cc2707f0de48b453b7112185eb7f45f0f12d58c26861285ca.
 *
 * Do not edit this file. Transport and feature policy belong in composition
 * adapters below Platform/Api.
 */
import createClient from "openapi-fetch";

export type components = {
  schemas: {
    "OrdersStatusResponse": {
      dependencies: Array<string>;
      module: string;
    };
    "ProblemDetails": {
      code: string;
      detail: string;
      errors: Array<{
        code: string;
        message: string;
        target?: string | null;
      }>;
      instance?: string | null;
      status: number;
      title: string;
      traceId: string;
      type: string;
    };
  };
};

export type ProblemDetails = components["schemas"]["ProblemDetails"];

export type paths = {
  "/api/v1/orders/status": {
    get: {
        responses: {
          "200": {
            content: {
              "application/json": components["schemas"]["OrdersStatusResponse"];
            };
          };
          "500": {
            content: {
              "application/problem+json": components["schemas"]["ProblemDetails"];
            };
          };
        };
      };
  };
  "/api/v1/orders/status/permissioned": {
    get: {
        responses: {
          "200": {
            content: {
              "application/json": components["schemas"]["OrdersStatusResponse"];
            };
          };
          "403": {
            content: {
              "application/problem+json": components["schemas"]["ProblemDetails"];
            };
          };
          "500": {
            content: {
              "application/problem+json": components["schemas"]["ProblemDetails"];
            };
          };
        };
      };
  };
};

export const generatedContractSha256 = "401e7e4d6cb38f1cc2707f0de48b453b7112185eb7f45f0f12d58c26861285ca";

export const createGeneratedClient = (
  baseUrl: string,
  fetcher: typeof fetch = fetch,
) => createClient<paths>({ baseUrl, fetch: fetcher });
