// Generated by NSwag.ConsoleCore 14.7.1 in client-only mode.
// The generated client owns HTTP DTOs and operations only.
// Source contract: contracts/openapi-v1.json.
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using System.Globalization;

namespace MartiX.FullStackTestApp.Web.Platform.Api;

public sealed class GeneratedClient(ApiTransport transport)
{
    private readonly ApiTransport apiTransport =
        transport ?? throw new ArgumentNullException(nameof(transport));
    private static readonly JsonSerializerOptions JsonOptions =
        new(JsonSerializerDefaults.Web);

    public async Task<OrdersStatusResponse> GetOrdersStatusAsync(CancellationToken cancellationToken = default)
    {
        using var httpRequest = new HttpRequestMessage(
            HttpMethod.Get,
            "/api/v1/orders/status");


        using var response = await apiTransport.SendAsync(
            httpRequest,
            new ApiRequestPolicy(RetrySafeRead: true),
            cancellationToken: cancellationToken);
        if (response.StatusCode == HttpStatusCode.Unauthorized)
        {
            throw await CreateApiExceptionAsync(
                response,
                cancellationToken,
                "session-expired");
        }
        if (response.StatusCode == HttpStatusCode.Forbidden)
        {
            throw await CreateApiExceptionAsync(
                response,
                cancellationToken,
                "access-denied");
        }
        if (!response.IsSuccessStatusCode)
        {
            throw await CreateApiExceptionAsync(response, cancellationToken);
        }
        return await response.Content.ReadFromJsonAsync<OrdersStatusResponse>(
            JsonOptions,
            cancellationToken)
            ?? throw new ApiException("ui.empty-response", response.StatusCode);
    }

    public async Task<OrdersStatusResponse> GetOrdersPermissionedStatusAsync(CancellationToken cancellationToken = default)
    {
        using var httpRequest = new HttpRequestMessage(
            HttpMethod.Get,
            "/api/v1/orders/status/permissioned");


        using var response = await apiTransport.SendAsync(
            httpRequest,
            new ApiRequestPolicy(RetrySafeRead: true),
            cancellationToken: cancellationToken);
        if (response.StatusCode == HttpStatusCode.Unauthorized)
        {
            throw await CreateApiExceptionAsync(
                response,
                cancellationToken,
                "session-expired");
        }
        if (response.StatusCode == HttpStatusCode.Forbidden)
        {
            throw await CreateApiExceptionAsync(
                response,
                cancellationToken,
                "access-denied");
        }
        if (!response.IsSuccessStatusCode)
        {
            throw await CreateApiExceptionAsync(response, cancellationToken);
        }
        return await response.Content.ReadFromJsonAsync<OrdersStatusResponse>(
            JsonOptions,
            cancellationToken)
            ?? throw new ApiException("ui.empty-response", response.StatusCode);
    }

    private static async Task<ApiException> CreateApiExceptionAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken,
        string fallbackCode = "ui.invalid-problem")
    {
        ProblemDetails? problem = null;
        try
        {
            problem = await response.Content.ReadFromJsonAsync<ProblemDetails>(
                JsonOptions,
                cancellationToken);
        }
        catch (JsonException)
        {
            // Keep malformed error payloads on the canonical failure path.
        }
        var code = response.StatusCode switch
        {
            HttpStatusCode.Unauthorized => "session-expired",
            HttpStatusCode.Forbidden => "access-denied",
            _ => problem?.Code ?? fallbackCode,
        };
        return new ApiException(
            code,
            response.StatusCode,
            problem);
    }

    private static string BuildPath(
        string template,
        params (string Name, object? Value)[] pathValues)
    {
        foreach (var (name, value) in pathValues)
        {
            var encodedValue = Uri.EscapeDataString(
                Convert.ToString(value, CultureInfo.InvariantCulture)
                ?? throw new InvalidOperationException(
                    $"Path parameter '{name}' cannot be null."));
            template = template.Replace(
                $"{{{name}}}",
                encodedValue,
                StringComparison.Ordinal);
        }

        return template;
    }

    private static string FormatHeaderValue(object? value, string name) =>
        Convert.ToString(value, CultureInfo.InvariantCulture)
        ?? throw new InvalidOperationException(
            $"Header parameter '{name}' cannot be null.");

    private static string BuildUri(
        string path,
        params (string Name, object? Value)[] queryValues)
    {
        var query = queryValues
            .Where(value => value.Value is not null)
            .Select(value =>
                $"{Uri.EscapeDataString(value.Name)}={Uri.EscapeDataString(Convert.ToString(value.Value, CultureInfo.InvariantCulture)!)}")
            .ToArray();
        return query.Length == 0
            ? path
            : $"{path}?{string.Join("&", query)}";
    }
}

public sealed record OrdersStatusResponse(
    IReadOnlyList<string> Dependencies,
    string Module
);

public sealed record ProblemDetails(
    string Code,
    string Detail,
    IReadOnlyList<ProblemError> Errors,
    string? Instance,
    int Status,
    string Title,
    string TraceId,
    string Type
);

public sealed record ProblemError(
    string Code,
    string Message,
    string? Target
);

public sealed class ApiException(
    string code,
    HttpStatusCode statusCode,
    ProblemDetails? problem = null)
    : Exception(code)
{
    public HttpStatusCode StatusCode { get; } = statusCode;
    public ProblemDetails? Problem { get; } = problem;
}
