/**
 * Generated from the OpenAPI 3.1 artifact contracts/openapi-v1.json.
 * Generator: openapi-typescript 7.13.0.
 * Runtime: openapi-fetch 0.17.0.
 *
 * Do not edit this file. Transport and feature policy belong in composition
 * adapters below Platform/Api.
 */
import createClient from "openapi-fetch";

export type ProblemDetails = {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  traceId?: string;
  code?: string;
  errors?: Record<string, string[]>;
};

export type paths = {
  "/api/v1/status": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              status: string;
            };
          };
        };
      };
    };
  };
};

export const createGeneratedClient = (baseUrl: string) =>
  createClient<paths>({ baseUrl });
