/**
 * Deterministic generated type surface for the reviewed OpenAPI 3.1 artifact.
 * The checked-in output is regenerated by the explicit client command.
 */
export type OpenApiDocumentVersion = "3.1.0";
export const openApiDocumentVersion: OpenApiDocumentVersion = "3.1.0";
