<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MartiX.AlphaRehearsal.Api/MartiX.AlphaRehearsal.Api.csproj" />
    <PackageReference Include="TUnit" Version="1.63.0" />
  </ItemGroup>
</Project>
