<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>MartiX.QuartzTestApp.Orders</RootNamespace>
    <AssemblyName>MartiX.QuartzTestApp.Orders</AssemblyName>
    <MartiXPlatformVersion>0.1.0-preview.1</MartiXPlatformVersion>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="MartiX.Platform" Version="$(MartiXPlatformVersion)" />
    <PackageReference Include="MartiX.Platform.AspNetCore" Version="$(MartiXPlatformVersion)" />
    <PackageReference Include="MartiX.Platform.Analyzers" Version="$(MartiXPlatformVersion)" PrivateAssets="all" />
    <PackageReference Include="MartiX.Platform.EntityFrameworkCore" Version="$(MartiXPlatformVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MartiX.QuartzTestApp.Tests" />
  </ItemGroup>
</Project>
